language: go
branches:
# 分支白名单限制：只有 master 分支的提交才会触发构建
  only:
    - master
install:
  # 安装最新的hugo
  # - go get github.com/gohugoio/hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/xianmin/hugo-theme-jane.git --depth=1 themes/jane
script:
  # 运行hugo命令
  - hugo
after_script:
  # 部署
  - cd ./public
  - git init
  - git config user.name "winsphinx"
  - git config user.email "winsphinx@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force "https://$GITHUB_TOKEN@${GH_REF}" master:gh-pages
  # - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags
env:
 global:
   # Github Pages
   - GH_REF: github.com/winsphinx/blog
deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  target-branch: gh-pages # 要将静态站点文件发布到哪个分支
  github-token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请，再到配置到Travis
  # fqdn:  # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支
