name: posts-commit

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.59.1'

      - name: Build
        run:  hugo --minify

      - name: Commit
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 0
